import React from "react"

class Etapa1 extends React.Component {

    render () {

        return (
            <div>

                <h1>ETAPA1 - DADOS GERAIS </h1>
                <h3>1. Qual é o seu nome?</h3>
                <input></input>

                <h3>Qual é a sua idade?</h3>
                <input></input>

                <h3>Qual é a sua escolaridade?</h3>
                <input></input>
           
           
           
            </div>
        )
    }
}

export default Etapa1